# Cloudflare Workers Configuration

name = "lisea-made-web"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "lisea_made_db"
database_id = "e8c34937-ea1f-400f-a455-f3e7f96913ae" # Bạn cần thay cái ID này sau khi tạo trên Dashboard

[vars]
# Giữ các biến môi trường nội bộ khác nếu có
NODE_ENV = "production"
